{
 "title": "Service-monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM worker WITH KEY=service"
   },
   {
    "name": "Inter",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d,60d,90d"
   }
  ]
 },
 "panels": [
  {
   "title": "resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "goroutine_num",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "goroutine_num",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process",
       "select": [
        [
         { "params": [ "goroutine_num" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "resource",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "cpu",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process",
       "select": [
        [
         { "params": [ "cpu_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process",
       "select": [
        [
         { "params": [ "mem_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "mem_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process",
       "select": [
        [
         { "params": [ "mem_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "cpu_percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "ansible",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "process",
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'ansible') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "cpu_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "ansible" }
       ]
      },
      {
       "alias": "cloudebent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'cloudevent') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "cloudevent" }
       ]
      },
      {
       "alias": "cloudid",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'cloudid') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "cloudid" }
       ]
      },
      {
       "alias": "cloudmon",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'cloudmon') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "cloudproxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'cloudproxy') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "devtool",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'devtool') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "k8s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'k8s') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "log",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'log') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "monitor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'monitor') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "notify",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'notify') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "region2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'region2') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "scheduledtask",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'scheduledtask') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "wenconsole",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'wenconsole') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "yunionconf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"cpu_percent\") FROM \"process\" WHERE (\"service\" = 'yunionconf') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "db_status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "idle",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "in_use",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "in_use" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "max_idle_closed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "max_idle_closed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "max_idle_time_closed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "max_idle_time_closed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "max_lifetime_closed",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "max_lifetime_closed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "max_open_connections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "max_open_connections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "open_connections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "open_connections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "wait_count",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "wait_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "select tag value" }
       ]
      },
      {
       "alias": "wait_duration",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "db_stats",
       "select": [
        [
         { "params": [ "wait_duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "worker_all",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "active",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "detach",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "detach_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "max_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "queue",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "queue_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "worker_queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "sync(AuthManager)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = '(AuthManager)sync_worker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "(AuthManager)sync_worker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "sync(EndpointChangeManager)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "worker_name",
         "operator": "=",
         "value": "(EndpointChangeManager)sync_worker"
        },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "sync(ServiceConfigManager)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "worker_name",
         "operator": "=",
         "value": "(ServiceConfigManager)sync_worker"
        },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "CloudProviderSynclnfoTaskWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'CloudProviderSyncInfoTaskWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "worker_name",
         "operator": "=",
         "value": "CloudProviderSyncInfoTaskWorkerManager"
        },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "CloudProviderSyncLocalTaskWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'CloudProviderSyncLocalTaskWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "worker_name",
         "operator": "=",
         "value": "CloudProviderSyncLocalTaskWorkerManager"
        },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "CronJobWorkers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'CronJobWorkers') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "CronJobWorkers" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "HttpGetRequestWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'HttpGetRequestWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "HttpGetRequestWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "HttpRequestWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'HttpRequestWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "HttpRequestWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "InformerWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'InformerWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "InformerWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "InternalHttpRequestWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'InternalHttpRequestWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        {
         "key": "worker_name",
         "operator": "=",
         "value": "InternalHttpRequestWorkerManager"
        },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "K8SEventHandlerWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'K8SEventHandlerWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "K8SEventHandlerWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "LocalTaskWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'LocalTaskWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "LocalTaskWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "LogClientWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'LogClientWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "LogClientWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "ModelTaskWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'ModelTaskWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "ModelTaskWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "NotifyClientWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'NotifyClientWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "NotifyClientWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "RequestWorker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'RequestWorker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "RequestWorker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "SubscriptionWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'SubscriptionWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "SubscriptionWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "TaskWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'TaskWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "TaskWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "client_catalog_listener_worker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'client_catalog_listener_worker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "client_catalog_listener_worker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "cloudAccountProbeWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'cloudAccountProbeWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "cloudAccountProbeWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "clusterSyncWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'clusterSyncWorkerManager') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "clusterSyncWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "opslog_query_worker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'opslog_query_worker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "opslog_query_worker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "opslog_write_worker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'opslog_write_worker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "opslog_write_worker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "policyFetchWorker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'policyFetchWorker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "policyFetchWorker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "realTimeUsageCalculateWorker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'realTimeUsageCalculateWorker') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "realTimeUsageCalculateWorker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syncWorkerManager-1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "query": "SELECT mean(\"active_worker_cnt\") FROM \"worker\" WHERE (\"worker_name\" = 'syncWorkerManager-1') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syncWorkerManager-1" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syncWorkerManager-2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syncWorkerManager-2" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syncWorkerManager-3",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syncWorkerManager-3" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syncWorkerManager-4",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syncWorkerManager-4" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syncWorkerManager-5",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syncWorkerManager-5" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "syslogSenderWorkerManager",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "syslogSenderWorkerManager" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "tenant_cache_sync_worker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "tenant_cache_sync_worker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "usageCalculateWorker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "worker",
       "select": [
        [
         { "params": [ "active_worker_cnt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "worker_name", "operator": "=", "value": "usageCalculateWorker" },
        { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "http request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "http request path hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"hit.2xx\")+mean(\"hit.4xx\")+mean(\"hit.5xx\")  FROM \"http_request\" WHERE (\"service\" =~ /^$server$/)  AND $timeFilter GROUP BY time($__interval),\"path\" ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "http request hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "2xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "hit.2xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "4xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "hit.4xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "5xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "hit.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "http request path duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.2xx\")+mean(\"duration.4xx\")+mean(\"duration.5xx\")  FROM \"http_request\" WHERE (\"service\" =~ /^$server$/)  AND $timeFilter GROUP BY time($__interval),\"path\" ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "http request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "2xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "duration.2xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "4xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "duration.4xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      },
      {
       "alias": "5xx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "select": [
        [
         { "params": [ "duration.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "5xx",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ansible",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "query": "SELECT mean(\"hit.5xx\") FROM \"http_request\" WHERE (\"service\" = 'ansible') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "hit.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "ansible" }
       ]
      },
      {
       "alias": "cloudebent",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'cloudevent') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "cloudevent" }
       ]
      },
      {
       "alias": "cloudid",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_request",
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'cloudid') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration.5xx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "service", "operator": "=", "value": "cloudid" }
       ]
      },
      {
       "alias": "cloudmon",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'cloudmon') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "cloudproxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'cloudproxy') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "devtool",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'devtool') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "k8s",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'k8s') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "log",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'log') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "monitor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'monitor') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "notify",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'notify') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "region2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'region2') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "scheduledtask",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'scheduledtask') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "wenconsole",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'wenconsole') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "yunionconf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration.5xx\") FROM \"http_request\" WHERE (\"service\" = 'yunionconf') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}