package types

const (
	ENV_AGENT_CONNECT = "YUNION_KUBE_AGENT_CONNECT"
	ENV_AGENT_TOKEN   = "YUNION_KUBE_TOKEN"
	ENV_AGENT_SERVER  = "YUNION_KUBE_SERVER"
	//ENV_AGENT_ROLE             = "YUNION_KUBE_ROLE"
	ENV_AGENT_ADDRESS          = "YUNION_KUBE_ADDRESS"
	ENV_AGENT_INTERNAL_ADDRESS = "YUNION_KUBE_INTERNAL_ADDRESS"
	ENV_AGENT_NODE_NAME        = "YUNION_KUBE_NODE_NAME"
)

const (
	ROLE_ETCD          = "etcd"
	ROLE_CONTROL_PLANE = "controlplane"
	ROLE_WORKER        = "worker"
)

const (
	AGENT_LABEL = "io.yunion.agent"
)
